### ISSUE TITLE
It was hanging when UTM being put in background

### ISSUE THREAD

**Issue by littlewey** [utmapp/UTM#261]
## Description
As titled, background mode is with issues, everything was hanging when UTM being put in background.
Please close if it’s duplicated.

## Minimal Reproduce

1. ssh to VM spawned by UTM when UTM is in front, run shell like:
```bash
while true
do
    echo it’s not hanging; date
done
```
2. We could see from ssh client screen it’s refreshing before putting UTM into background

3. Put UTM in background, we could see ssh client hanging 

4. Switch UTM back in front, the while script was resumed ;-)

> I recorded this screen shot video here: https://vimeo.com/407004796 

## Environment Information 
```yaml
UTM version: 0.9
Distribution: AltStore source
Host Info:
    Host OS:
        name: iPad OS
        version: 13.4.1 (17E262)
    Host Machine:
        name: iPad Pro Gen2
        type: A1671
```

Thanks!
BR//Wey
