### ISSUE TITLE
Networking not working with Ubuntu guest under 3.2.4

### ISSUE THREAD

**Issue by freebrowser1** [utmapp/UTM#4115]
When using a Ubuntu 22.04 VM I cannot get networking in UTM 3.2.4. 
The same VM works flawlessly under 3.1.5.
I use 'Bridged' using the 192.168.0.x subnet.
I followed the instructions on this page: http://mac.getutm.app/gallery/ubuntu-20-04

Before the upgrade of the VM to 22.04 I had the same issue 20.04 under UTM 3.2.3. 

```
ip link show 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 96:f4:87:c7:d3:64 brd ff:ff:ff:ff:ff:ff
```
Then I edited the configuration in the VM:

`sudo nano /etc/netplan/00-installer-config.yaml`

```
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s10:
      dhcp4: true
  version: 2
```

So I added enp0s9:

```
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s10:
      dhcp4: true
  version: 2
    enp0s9:
      dhcp4: true
  version: 2
```
but the network did still not work after reboot.

**Comment by freebrowser1** [comment]
WITHDRAWN.
When I set 
```
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s9:
      dhcp4: true
  version: 2
```
just this in `/etc/netplan/00-installer-config.yaml`
it does work.
So this ticket can be closed.
